name: python test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install pytest
        run: python -m pip install pytest

      - name: run python test
        run: pytest